### ISSUE TITLE
Third level incorrect in Filters tree 

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-ui#18]
@charlie86 

A few things I observed w.r.t. `Filters` tree with latest commit suggestion by me (https://github.com/Paradigm4/revealgenomics-ui/commit/781d1052ec90405552df7470daa0b3f18cf9007f):

The `Filters` tree shows a level as: 
- Variant
    - Single Nucleotide Variant
          - Variant
          - Variant
          - Variant

i.e. the pipeline names do not show up in the third level

**Comment by ksens** [comment]
Note that similar error occurs for other entities, though I have not listed that above.

**Comment by charlie86** [comment]
@ksens this is now fixed

**Comment by ksens** [comment]
Yup, fixed.
