### ISSUE TITLE
Avoid writing username and password in the code

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-ui#2]
@charlie86 

Instead of writing the username and password in the code, I would suggest reading the username and password on the fly from a config file. 

Will suggest an implementation via a PR. Will let you review the PR.

**Comment by ksens** [comment]
w.r.t. the above referenced commit, you will see that I read a file `~/revealgenomics-ui-config.json` file into memory. The file has the following format:

```
{
  "username": "<ENTER_USERNAME_HERE>",
  "password": "<ENTER_PASSWORD_HERE>"
}
```

**Comment by charlie86** [comment]
merged!
