### ISSUE TITLE
[Login] After user successfully signs in, expect "Log out" button that falls back to default user

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-ui#25]
Currently after successful login, the logged in user's name is displayed. Clicking that allows to login as another user. 

Expect a logout button beside the username. 
<img width="152" alt="log-out-sign" src="https://user-images.githubusercontent.com/13973052/49566000-38793400-f94f-11e8-987e-502383db6880.png">
(ignore the settings sign)

**Comment by ksens** [comment]
Thanks for the changes. One more thing to refine:

## Current state
Hitting Logout currently pops up a Login dialog. If I hit "Dismiss" on that, then it falls back to the public user. 

## Requested

The Login dialog does not need to appear. Hitting "Logout" should directly get back to "Dashboard" view of public user.

**Comment by tcash21** [comment]
This works now by switching to reactiveValues for both the connection and logged_user objects so that we can change them as needed. Please review / test.

**Comment by ksens** [comment]
Last reported issue was fixed with https://github.com/Paradigm4/revealgenomics-ui/commit/69c3f4f4476996fb80c5ab33bef80144a913818f by @charlie86 

Closing the issue. Thanks.
