### ISSUE TITLE
Change Heatmap colors and add labels

### ISSUE THREAD

**Issue by tcash21** [Paradigm4/revealgenomics-ui#36]
Change Heatmap colors (red and green) and add labels

**Comment by ksens** [comment]
Also we discussed trying to flip the scatter and box plots by 90-deg. 

Can you please keep an easily accessible variable in the code. that lets me toggle between the two states? Eventually we might even surface that option to the UI (for now, it is OK to keep it in the code).

**Comment by tcash21** [comment]
Sure thing. You'd just need to remove the `+ theme()` part from this code:

```
gg <- ggplot(plot_df, aes(x = gene, y = expression)) +
      geom_boxplot() +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

**Comment by tcash21** [comment]
This is complete.
