### ISSUE TITLE
List of packages required for revealgenomics UI

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-ui#4]
@charlie86 

Nit: Looking for a one stop documentation that lists installation commands R packages required. For example, while testing the app on one machine, I realized that I needed to install `future`, `tidyverse`. A one stop shop would help. 

```R
install.packages(c('repo1', 'repo2')) # all packages that are available from CRAN
devtools::install_github('orgXX/repoA') # from Github
devtools::install_github('orgYY/repoB') # another package from Github
```

And a table that lists the minimum version or Github Sha (if required). Really helps figure out issues later on.

**Comment by charlie86** [comment]
All packages required are now in the readme

**Comment by ksens** [comment]
Thanks. Closing. 

PS: Moved the required packages to `dashboard` directory.
