### ISSUE TITLE
App crashes when username / password combination is incorrect

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-ui#5]
@charlie86 

Right now, if the username-password combination is incorrect, then the UI crashes. 

There should be some form of exception handling mechanism so that an erroneous login attempt reverts back to the default user.

**Comment by charlie86** [comment]
fixed!

**Comment by ksens** [comment]
Now it gives a meaningful error. That's good.

However the app should then fall back to the default user. Currently that connection seems to be broken. Reopening the issue.

**Comment by charlie86** [comment]
@ksens This should now be fixed

**Comment by ksens** [comment]
Yup, fixed.
