### ISSUE TITLE
Pipeline and Study trees not working for default user at deployment A

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-ui#6]
@charlie86 

I tested your current code on one of our deployments of the API. 

The app starts up most of the way (I see the correct queries being executed in the scidb logs), the dashboard is populated with the correct numbers. However nothing shows up in the Pipeline (aka Filters) or Study tree (the Study tree is populated with a correct study count though). 

I started going through the code around [this line for the filter tree](https://github.com/Paradigm4/revealgenomics-ui/blob/master/tcb/app.R#L369) and [this line for the studies tree](https://github.com/Paradigm4/revealgenomics-ui/blob/master/tcb/app.R#L463). In fact, I stepped into debugger and the dataframe (with top, middle, bottom), list and subsequent JSON seems to be formulated OK. However the final output is blank. 

Will probably have to schedule a separate TCon to debug this. Meanwhile I will test this on another deployment and see what I get.

**Comment by charlie86** [comment]
fixed

**Comment by ksens** [comment]
@charlie86 

The app does start up for the default user at deployment A. Some entries go all the way down to pipeline name, but some stop at "Gene Expression" and then do not go down to the pipeline name. I can show you during our Monday meeting. 

Also as part of best practises can you include the issue number in your commit message. That way the commit relevant to this fix would get tagged in this thread. 

e.g. a commit message like the following gets tagged automatically to this thread

```
resolve login issue (fix for #6)
```
