### ISSUE TITLE
selected_study() not returning unique study

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics-ui#9]
From what I understand, the function `selected_study()` defined in the app is important as this is then used to link to downstream API calls. 

At deployment B, I faced an error, and then started debugging. Pasting some debug outputs

```R
selected_study()$name
# [1] "TNsnv: DNA-mutations - filter 1" "TNsnv: DNA-mutations - filter 1" "TNsnv: DNA-mutations - filter 1"
# [4] "TNsnv: DNA-mutations - filter 1"

selected_study()$dataset_id
# [1] 1 2 7 7
```

I think there is an incorrect assumption that is creating the issue -- the same pipeline name can exist in multiple studies. Matching must be done based on all three levels of the tree (or at least the last two):

- project name
- study name
- pipeline name

**Comment by ksens** [comment]
@charlie86 

I tested on deployment A, and got a crash. 

Debugged the code and saw the crash happening in a `mutate` call. If I replace the `mutate` with more generic R calls, it works OK. Will submit a PR to show you my change -- you can review and integrate. 

After my change, I do not see the error with non uniqueness of `selected_study()` any more.

**Comment by ksens** [comment]
Of course, note that I do not really grok the reason for the error. I would have thought that your original call using `mutate` and my call using generic R calls should produce the same result. 

Anyway if it works OK on your end, it might be OK to close this issue after merging my PR, and then focus on other issues. 

Thanks again.

**Comment by charlie86** [comment]
@ksens Thanks for catching this! I'll take a look tonight and get moving on the other issues.
